Add StyleGuide.md
fujitsu-cdf/dashboard pull request #12
Opened 2020-12-17 02:48 UTC by Martsings

# Changes

Add StyleGuide.md as the reference for Japanese localization

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

2020-12-17 02:59 UTC, yamaken1343 approved these changes

2020-12-18 02:42 UTC, kobaji requested changes

2020-12-18 02:42 UTC, kobaji commented on docs/dev/localization/Japanese/StyleGuide.md
> +# 翻訳スタイルガイド
- ファイル名についてです。小林が提案したものなので申し訳ないが、StyleGuideよりもstyle-guide.mdの方が良いと思いました。
  - https://zinrai-translation.bicc.css.fujitsu.com/# で翻訳すると「スタイルガイド」は"style guide"と出ます。ググった場合も同じように"style guide"が多い("styleguide"もなくはない)
  - Tektonダッシュボードの[このフォルダー](https://github.com/tektoncd/dashboard/tree/master/docs)を見ると、ファイル名はキャメルケース("StyleGuide.md")よりもケバブケース"style-guide.md"

2020-12-18 02:42 UTC, kobaji commented on docs/dev/localization/Japanese/StyleGuide.md
> +# 翻訳スタイルガイド
- PRのタイトルも"Add style-guide.md or Japanese Translation"にするのはいかがでしょうか。

2020-12-18 02:42 UTC, kobaji commented on docs/dev/localization/Japanese/StyleGuide.md
> +# 翻訳スタイルガイド
- 完全コピペではなく、参考にする程度にしてほしいです。
  - 一般的にこういうガイドラインは必要なので、参考にするのは問題ない。
  - ただ、完全コピペだとトラブルになるかも。安全サイドで考えたい。
  - 私のこの指摘は曖昧ですので、必要であれば会話させてください。
  - @yamaken1343 のご意見も伺いたい…。

2020-12-18 02:42 UTC, kobaji commented on docs/dev/localization/Japanese/StyleGuide.md
> +| （〇〇〇。） | （〇〇〇。） |
- `（〇〇〇。）`のあるべき姿も`（〇〇〇。）`になっています。正しくは`（〇〇〇）。`ですかね。

2020-12-18 02:55 UTC, Martsings commented on docs/dev/localization/Japanese/StyleGuide.md
> +# 翻訳スタイルガイド
見た目上自分も少し不安でしたので、項目やタイトルの設定について独特の意見があればいただきたいです。

2020-12-18 02:55 UTC, kobaji commented
- 書かれている内容については必要十分だと思います。<br>
  - `記号類は全角で表記`ということですので、現在の messages_ja.jsonについて、GUIに表示される部分の記号が全角になっていることを確認する必要があります(別途指摘しています)。
- 体裁について指摘を数点コメントしました。

2020-12-18 02:58 UTC, kobaji requested changes

2020-12-18 02:58 UTC, kobaji commented on docs/dev/localization/Japanese/StyleGuide.md
> +## 基本方針
書かれていること自体は問題ないと思います。(フォーマット、字句がコピペになっているので、そこは変えていただきたいですが(別途指摘済)。)

書かれていることが、messages_ja.jsonで反映されているかご確認お願いします。

2020-12-18 04:08 UTC, kobaji commented on docs/dev/localization/Japanese/StyleGuide.md
> +## 基本方針
ちなみに。

- `句読点は「、」と「。」を使用`

読点に「,」が使われていないことは、以下で確認済です。句点は確認未です。
VSCodeで`,`を検索したら313件、`,\n`で検索したら308件ヒットした(json定義は3～310行目の308件なので、json定義以外の`,\n`は存在しない)。差異5件は以下(正規表現`[^"],`で検索)で、いずれも翻訳に影響しない

```
      $ cat -n src/nls/messages_ja.json | grep "[^\"],"
    12      "carbon.table.batch.item.selected": "{totalSelected, plural, =0 {0 項目} one {1 項目}}が選択されました",
    13      "carbon.table.batch.items.selected": "{totalSelected, plural, other {# 項目}}が選択されました",
   192      "dashboard.pipelineRun.pipelineTaskName.retry": "{pipelineTaskName}(retry{retryNumber,number})",
```

- `記号類は全角で表記`

コロンについて、`：`(全角コロン)が使われているかを確認したところ、不適切に半角コロン(`:`)が使われていることを確認しました。

VSCodeで半角`:`を検索したら315件、 `":`を検索したら310件ヒットした(json定義は2～311行目の310件なので、json定義以外の`":`は存在しない)。差異5件は以下(正規表現`[^"]:`で検索)で、22行目と205行目に修正が必要。

```
      $ cat -n src/nls/messages_ja.json | grep "[^\"]:"
    22      "dashboard.about.missingProperties": "次のものが見つかりません:{errorsFound}",
   145      "dashboard.labelFilter.invalid": "フィルタはlabelKey:labelValueの形式で、使用可能なラベル文字を含む必要があります",
   146      "dashboard.labelFilter.invalidLength": "フィルタはlabelKey:labelValueの形式で、64文字未満である必要があります",
   147      "dashboard.labelFilter.searchPlaceholder": "labelKey:labelValueの形式で検索",
   205      "dashboard.rerun.error": "{runName}の再実行中にエラーが発生しました：詳細については、ダッシュボードログを確認してください。ステータスコード: {statusCode}",
```

2020-12-18 04:19 UTC, kobaji commented
成果物と直接関係ないですが、、

- http://10.125.71.194:3000/issues/9232 の説明欄に、内部レビュー用PRのURLを記載するところがあります。本PRのURLを貼っておいていただけますか。
- `9232-wk`と`9232-pr`のブランチが古いかもしれません(最新コミットではmessages_ja.jsonに`paramater`が消えているはず)。もしかしたらコミュニティ版にPR発行するときにコンフリクトが起きるかもしれません。起きそうであれば対処しましょうか(別途相談)。

2020-12-18 04:20 UTC, kobaji commented on docs/dev/localization/Japanese/StyleGuide.md
> +# 翻訳スタイルガイド
成果物と直接関係ないですが、、

- http://10.125.71.194:3000/issues/9232 の説明欄に、内部レビュー用PRのURLを記載するところがあります。本PRのURLを貼っておいていただけますか。
- `9232-wk`と`9232-pr`のブランチが古いかもしれません(最新コミットではmessages_ja.jsonに`paramater`が消えているはず)。もしかしたらコミュニティ版にPR発行するときにコンフリクトが起きるかもしれません。起きそうであれば対処しましょうか(別途相談)。

2020-12-18 04:24 UTC, Martsings commented on docs/dev/localization/Japanese/StyleGuide.md
> +## 基本方針
了解しました。翻訳時にはすべて全角するつもりでしたが、このように漏れがありそうです。
小林さんがチェックした以外の部分について確認します。

2020-12-18 05:01 UTC, Martsings commented on docs/dev/localization/Japanese/StyleGuide.md
> +# 翻訳スタイルガイド
対応済み

2020-12-18 05:02 UTC, Martsings commented on docs/dev/localization/Japanese/StyleGuide.md
> +# 翻訳スタイルガイド
対応済み

2020-12-18 05:10 UTC, Martsings commented on docs/dev/localization/Japanese/StyleGuide.md
> +| （〇〇〇。） | （〇〇〇。） |
対応済み

2020-12-18 05:11 UTC, Martsings commented on docs/dev/localization/Japanese/StyleGuide.md
> +# 翻訳スタイルガイド
自分の判断で修正しました。次回のレビューで確認をお願いします。

2020-12-18 05:17 UTC, Martsings commented on docs/dev/localization/Japanese/StyleGuide.md
> +# 翻訳スタイルガイド
一番目について対応済み

2020-12-18 06:24 UTC, Martsings commented on docs/dev/localization/Japanese/StyleGuide.md
> +## 基本方針
以下はVScodeで確認した結果です。

- `句読点は「、」と「。」を使用`
読点に「.」が使われていないことは確認しました。

- `記号類は全角で表記`
`?`：半角`?`が0件だと確認しました。

`()`：半角`()`が8件だと確認しました。191行と291行は英文をそのまま流用したので、修正は不要です。それ以外は修正が必要です。
```
65 "dashboard.createPipelineRun.serviceAccountHelperText": "選択したServiceAccount(選択していない場合はデフォルト)に、PipelineRunの作成およびPipelineRunに関するリソースに対する権限があることを確認してください。",
93 "dashboard.createTaskRun.serviceAccountHelperText": "選択したServiceAccount(選択していない場合はデフォルト)に、TaskRunの作成およびTaskRunに関するリソースに対する権限があることを確認してください。",
94 "dashboard.createTaskRun.timeoutHelperText": "TaskRunタイムアウト(分)",
132 "dashboard.importResources.repo.helperText": "適用するYAML定義の場所(Git URLをサポート)",
135 "dashboard.importResources.serviceAccount.helperText": "リソースを適用するPipelineRunが(上のNamespaceから)実行するServiceAccountです。Gitリポジトリ内のTektonリソースを含め、選択したServiceAccount(選択していない場合はデフォルト)に、PipelineRunの作成およびPipelineRunに関するリソースに対する権限があることを確認してください。",
191 "dashboard.pipelineRun.pipelineTaskName.retry": "{pipelineTaskName}(retry{retryNumber,number})",
291 "dashboard.triggerDetails.interceptorTitle": "{interceptorNumber}. ({interceptorType}) {interceptorName}",
```

- `英単語と日本語の間に半角スペースは不要`
[a-zA-Z] [^a-zA-Z{]を検索し、1件だと確認しました。修正が必要です。
```
187 "dashboard.pipelineRun.failedMessage": "PipelineRun 詳細をロードできません：{reason}",
```

2020-12-18 06:46 UTC, Martsings commented on docs/dev/localization/Japanese/StyleGuide.md
> +## 基本方針
以下について対応済み
- 半角コロン`:`
- 英単語と日本語の間に半角スペース

2020-12-18 09:18 UTC, kobaji commented on docs/dev/localization/Japanese/StyleGuide.md
> +# 翻訳スタイルガイド
- 1個目：対応されていることを確認しました。
- 2個目：これでコンフリクトは起こらなくなると思います。ありがとう。(もし発生しそうだったら、コミュニティと相談しましょう…！)

2020-12-18 09:35 UTC, Martsings commented on docs/dev/localization/Japanese/StyleGuide.md
> +# 翻訳スタイルガイド
なぜかコミュニティと1commit遅れとなっていますね。9232-prブランチは完全に同じくなりました。来週ちょっと調査します。

2020-12-18 09:37 UTC, kobaji commented on docs/dev/localization/Japanese/StyleGuide.md
> +## 基本方針
調査も必要十分だと思います。馬さんが調べてくれたもの、小林が調べたものを以下で一覧にしています。

http://10.125.71.194:3000/issues/9232#note-10

2020-12-18 09:37 UTC, kobaji approved these changes

2020-12-22 06:57 UTC, closed without merging