Add term.tsv for Japanese translation
fujitsu-cdf/dashboard pull request #17
Opened 2021-01-25 00:52 UTC by Martsings

# Changes

Add term.tsv as a reference Japanese translation.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

2021-01-25 09:10 UTC, kobaji requested changes
作成ありがとうございます。パッと見て気になったところをコメントしました。
お手数おかけしますがご確認よろしくお願いいたします。

`something 問題`という列(102行目)がどのような過程で生まれたのか、会話で質問させてください。1/26に声掛けします(できれば…！)

2021-01-25 09:10 UTC, kobaji commented on docs/dev/localization/Japanese/term.tsv
> +templatea   テンプレート
`templates`の誤りでしょうか？

2021-01-25 09:10 UTC, kobaji commented on docs/dev/localization/Japanese/term.tsv
> +次?
> ? がついている用語は決められなく意見を伺いたいと思っています。

mattermostにある上記の記述ですが、
英語が決められないということでしょうか。それとももともと英単語があったのでしょうか？

2021-01-25 09:10 UTC, kobaji commented on docs/dev/localization/Japanese/term.tsv
> +something   問題?
ご認識いただいていると思いますが、something に対して 問題と訳すのは不適切ですよね。
みんなの自動翻訳で抽出したとき既にsomething=問題と表示されていましたでしょうか？
別途口頭で会話させてください。(1/26にこちらから声かけできるよう努めます…！)

小林用メモ：
どういうプロセスで something = 問題と抽出されたのか。
この行だけ見たら、something wrong = 問題と置き換えてしまってよいようにも見える。

2021-01-25 09:10 UTC, kobaji commented on docs/dev/localization/Japanese/term.tsv
> +documentation   マニュアル?
マニュアルかドキュメントにしたいですね。個人的にはドキュメントの方がよい(マニュアルはドキュメントに含まれているため、ドキュメントと訳しておけば問題ないと思うため)と思います。馬さんの考えを聞かせていただきたいです。

2021-01-25 09:10 UTC, kobaji commented on docs/dev/localization/Japanese/term.tsv
> +documentation   マニュアル?
提案ですが、これも表記ゆれのように見えなくはないですね。マニュアルかドキュメントかで揃えた方が良い気もします。

https://github.com/fujitsu-cdf/dashboard/blob/21a84e30ad13d373163792569242cf24f2e64567/src/nls/messages_ja.json#L146

https://github.com/fujitsu-cdf/dashboard/blob/21a84e30ad13d373163792569242cf24f2e64567/src/nls/messages_ja.json#L215

2021-01-25 09:10 UTC, kobaji commented on docs/dev/localization/Japanese/term.tsv
> +something   問題?
独り言。something went wrongならここにあるのか。

https://github.com/fujitsu-cdf/dashboard/blob/21a84e30ad13d373163792569242cf24f2e64567/docs/dev/localization/Japanese/term.tsv#L146

2021-01-25 09:10 UTC, kobaji commented on docs/dev/localization/Japanese/term.tsv
> +error   エラー
全体的なことです。
http://10.125.71.194:3000/issues/9199 に「[06_messages_対訳用語抽出結果.tsv](http://10.125.71.194:3000/attachments/4273)」を添付していますが、この結果が用語集に含まれていない意図を教えていただけますでしょうか。
(入れなければいけない、というわけではないですが、入れるものだと認識していたので、気になっています。)

2021-01-25 09:10 UTC, kobaji commented on docs/dev/localization/Japanese/term.tsv
> +error   エラー
全体的なことです。

- tsvファイルは<tab>が入ると思いますが、それが見えないです。修正をお願いします。
  - もし<tab>が入れられない、削除されてしまうなど事情があれば相談してください。

ちなみに[HyperLedgerのterm.tsv](https://github.com/linuxfoundation-jp/HL_Fabric_Doc-Jp/blob/36c58085a6101811e4650293bd16ede0c184abc7/term.tsv)は、サクラとかにコピペすると<tab>が入っています。

2021-01-25 09:10 UTC, kobaji commented on docs/dev/localization/Japanese/term.tsv
> +error   エラー
全体的なことです。

- [チケット#9199注記#18](http://10.125.71.194:3000/issues/9199#note-18)についてのコメント失礼します。
  - 「小林さんが書いた流れ」がどこを指すのかわかるようにしてほしいです。リンクを貼るなど。次回以降用語集を作成する人は、どこを参照したのか知りたいと思います。

2021-01-25 09:10 UTC, kobaji commented on docs/dev/localization/Japanese/term.tsv
> +error   エラー
全体的なことです。

- [チケット#9199注記#18](http://10.125.71.194:3000/issues/9199#note-18)についてのコメント失礼します。
  - 対訳集を破棄することはわかりましたが、その理由を記載しておいてもらいたいです。確か「対訳集は文レベルの訳を集めたものだが、みんなの自動翻訳では抽出精度が低く、次回以降の翻訳に役立てられない」とかだった気がします(違ったらごめんなさい)。今後報告資料に報告する必要が出てくるかもしれないので、事実が書いてあると助かります。

2021-01-25 09:17 UTC, yamaken1343 commented on docs/dev/localization/Japanese/term.tsv
> +documentation   マニュアル?
ドキュメントのほうがよいかなと思いました

2021-01-25 09:19 UTC, yamaken1343 commented on docs/dev/localization/Japanese/term.tsv
> +server URL  サーバURL
助詞をいれて「サーバのURL」のほうがそれっぽいかなと思いました

2021-01-25 09:22 UTC, yamaken1343 commented on docs/dev/localization/Japanese/term.tsv
> +default デフォルト  デフォルト値
2個書いてあるのはフォーマット上良いですか？

2021-01-26 00:28 UTC, Martsings commented on docs/dev/localization/Japanese/term.tsv
> +templatea   テンプレート
はい、そうです。修正しました。

2021-01-26 00:29 UTC, Martsings commented on docs/dev/localization/Japanese/term.tsv
> +次?
ここでは、訳にあっている英単語が見つからません。

2021-01-26 00:29 UTC, Martsings commented on docs/dev/localization/Japanese/term.tsv
> +something   問題?
すみません、この行は削除するのを忘れました。修正しました。

2021-01-26 00:31 UTC, Martsings commented on docs/dev/localization/Japanese/term.tsv
> +documentation   マニュアル?
自分もドキュメントに修正したほうが良いと思います。
messagesのところも修正します。

2021-01-26 01:13 UTC, Martsings commented on docs/dev/localization/Japanese/term.tsv
> +error   エラー
> 06_messages_対訳用語抽出結果.tsv

漏れがあると思います。ただし、基本その内容が入っていると思いますが、含まれていないというのはどういうものでしょうか？

> tsvファイルはが入ると思いますが、それが見えないです。

このコメントの意図がわかりませんでした。必要であれば会話します。

> チケット#9199注記#18

チケットの記載を修正します。確認をお願いします。

2021-01-26 01:15 UTC, Martsings commented on docs/dev/localization/Japanese/term.tsv
> +default デフォルト  デフォルト値
みんなの翻訳でインポート時に問題あるかどうかは検証が必要ですが、リポジトリにおけるものとしてはこのフォーマットで行きます。

2021-01-26 01:16 UTC, Martsings commented on docs/dev/localization/Japanese/term.tsv
> +server URL  サーバURL
messagesでこれと似たような翻訳がいくつかありました。もし修正ならそれらも修正したほうが良いと感じます。
@kobaji ご意見をいただけないのでしょうか

2021-01-26 05:59 UTC, kobaji commented on docs/dev/localization/Japanese/term.tsv
> +次?
すみませんが自分が勘違いしてしまっている気がするので、会話で質問させてください。

2021-01-26 06:05 UTC, kobaji commented on docs/dev/localization/Japanese/term.tsv
> +error   エラー
> 漏れがあると思います。ただし、基本その内容が入っていると思いますが、含まれていないというのはどういうものでしょうか？

別途会話させてください。

> このコメントの意図がわかりませんでした。必要であれば会話します。

すみません…`<tab>`って文字列を入れていたのですが、バッククォート`` ` ``で囲ってあげなかったので見えなくなってしまっていましたね…。
⇒コメントを修正しました。必要であれば会話します。

> チケットの記載を修正します。確認をお願いします。

ありがとうございます。確認し、チケットについてクローズし、追加指摘はありません。

2021-01-26 06:12 UTC, kobaji commented on docs/dev/localization/Japanese/term.tsv
> +server URL  サーバURL
会話で意識合わせしましょうか。

2021-01-26 06:20 UTC, Martsings commented on docs/dev/localization/Japanese/term.tsv
> +次?
”次”を削除

2021-01-26 06:32 UTC, Martsings commented on docs/dev/localization/Japanese/term.tsv
> +error   エラー
> 06_messages_対訳用語抽出結果.tsv

大文字と小文字の翻訳時の検証！

2021-01-26 06:37 UTC, Martsings commented on docs/dev/localization/Japanese/term.tsv
> +server URL  サーバURL
"の"へ修正

2021-01-26 06:59 UTC, kobaji requested changes

2021-01-26 06:59 UTC, kobaji commented on docs/dev/localization/Japanese/term.tsv
> +error   エラー
口頭でお伝えしましたが、また本質ではなく申し訳ないですが、、、

https://github.com/fujitsu-cdf/dashboard/blob/21a84e30ad13d373163792569242cf24f2e64567/src/nls/messages_ja.json#L57

https://github.com/fujitsu-cdf/dashboard/blob/21a84e30ad13d373163792569242cf24f2e64567/src/nls/messages_ja.json#L65

空文字と、英語をそのまま取り入れたものが混在しています。空文字に統一してください。

参考
https://github.com/tektoncd/dashboard/tree/master/docs/dev#i18n によると、

messages_en.jsonにあるvalueの作られ方：
各jsファイルにある`id`と`defaultMessage`が1:1対応したものがmessages_en.jsonが作られます。

またソースは見つけられませんでしたが、実績から…
messages_ja.jsonのvalueを空文字にした場合：messages_en.jsonのvalueがそのまま挿入されます。

①messages_ja.jsonのvalueにmessages_en.jsonのvalueをコピペした場合
②messages_ja.jsonのvalueを空文字にした場合

すみません、あとで最後まで書きます。

2021-01-26 07:48 UTC, Martsings commented on docs/dev/localization/Japanese/term.tsv
> +error   エラー
空文字に修正しました。

2021-01-27 02:41 UTC, kobaji commented on docs/dev/localization/Japanese/term.tsv
> +error   エラー
メモ
指摘したことの反映状況

- 大文字と小文字：resolve
- tab：確認できたらresolveする
- チケット：resolve

2021-01-27 03:13 UTC, kobaji commented on docs/dev/localization/Japanese/term.tsv
> +error   エラー
- 空文字にする必要があるが空文字になっていない箇所の有無
  - 242行目`Pipeline`は空文字にしないでしょうか(ちなみに。enは現在`Pipeline`だが、今後`Pipelines`になる可能性がある。その場合日本語では単数表示するというルールに違反してしまうため、あえて`Pipeline`のまま記載した、など理由があれば空文字にしない＝修正しないという選択もよいと思います。ただその場合、en244行目の`ServiceAccount`をja244行目で""にしているのは整合しないですね…)。
  - 他はコメントなし
- 空文字にしてはいけないのに空文字になった箇所の有無
  - 確認中

2021-01-27 03:27 UTC, Martsings commented on docs/dev/localization/Japanese/term.tsv
> +error   エラー
242行目は漏れでした。修正します。

2021-01-27 04:13 UTC, kobaji requested changes

2021-01-27 04:13 UTC, kobaji commented on docs/dev/localization/Japanese/term.tsv
> +error	エラー
PRのタイトルをより正確にするために、以下にしませんか？

Add term.tsv for Japanese translation
↓
Add term.tsv for Japanese translation and Modify messages_ja.json

2021-01-28 00:49 UTC, Martsings commented on docs/dev/localization/Japanese/term.tsv
> +error	エラー
はい、以下のように修正しました。
```
Add term.tsv for Japanese translation and modify messages_ja.json
```

2021-01-28 00:59 UTC, kobaji approved these changes

2021-01-28 01:14 UTC, merged