Update messages_ja.json & term.tsv
fujitsu-cdf/dashboard pull request #23
Opened 2021-03-05 06:07 UTC by mishima-haruka

# Changes

Update messages_ja.json & term.tsv
add translation terms to empty columns

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

2021-03-08 06:51 UTC, kobaji requested changes
まずmessages_ja.jsonについてのみレビューしました。これから翻訳DB(term.tsv)のレビューに入ります。

dashboardを実際に動かしてメッセージを確認したいけど、うまくできない、などありましたらご相談ください。

2021-03-08 06:51 UTC, kobaji commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
「空文字("")になっている用語のうち、翻訳するかしないかを決めた基準」を教えていただきたいです。

⇒三島さんから[mattermost](http://10.125.71.194:8066/fjsghd/pl/h7n3313tzid33jetoqmeeyd9go)で以下のコメントを得られ、納得したためresolveする

> 英語版の内容を見てkubernetesなどで使われている固有名詞などだった場合はそのままにしています。
また、日本語に訳すよりも英語のままの方が良いだろうと判断したものも""にしています。(こちらの判断基準については明確なものはないです)

2021-03-08 06:51 UTC, kobaji commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
変更していない行に対してコメントできなさそうなので、ここでコメントします。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_ja.json#L21

ここは変更していないようですが、「ログアウトURL」にしない理由はありますでしょうか。
以下と整合させるのであれば、「ログアウトURL」の方がしっくりきます。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_ja.json#L104

2021-03-08 06:51 UTC, kobaji commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
変更していない行に対してコメントできなさそうなので、ここでコメントします。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_ja.json#L24

Trueを翻訳しない理由を教えていただけますか。
(翻訳しないのが妥当かどうか判断できないため質問させていただきました)

2021-03-08 06:51 UTC, kobaji commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
変更していない行に対してコメントできなさそうなので、ここでコメントします。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_ja.json#L44

以下のパイプラインリソースの作成画面で使われていますが、"パイプラインリソース名を入力"が適切かと思います。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/containers/CreatePipelineResource/UniversalFields.js#L41-L42

2021-03-08 06:51 UTC, kobaji commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
変更していない行に対してコメントできなさそうなので、ここでコメントします。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_ja.json#L48

以下のパイプラインリソースの作成画面で使われていますが、"パイプラインリソースのリビジョンを入力"が適切かと思います。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/containers/CreatePipelineResource/GitResourceFields.js#L30-L31

2021-03-08 06:51 UTC, kobaji commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
変更していない行に対してコメントできなさそうなので、ここでコメントします。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_ja.json#L53

以下のパイプラインリソースの作成画面で使われていますが、"パイプラインリソースのURLを入力"が適切かと思います。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/containers/CreatePipelineResource/UniversalFields.js#L97-L98

2021-03-08 06:51 UTC, kobaji commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
変更していない行に対してコメントできなさそうなので、ここでコメントします。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_ja.json#L61

下記に合わせて「PipelineRunを作成」が適切かと思います。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_ja.json#L51

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_ja.json#L77

2021-03-08 06:51 UTC, kobaji commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
変更していない行に対してコメントできなさそうなので、ここでコメントします。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_ja.json#L89

[スタイルガイド.md](https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/docs/dev/localization/Japanese/style-guide.md)にあるように、`:`(半角コロン)は、日本語では全角にするルールなので`：`(全角コロン)にしてください。

参考： messages_en.json
https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_en.json#L89

2021-03-08 06:51 UTC, kobaji commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
変更していない行に対してコメントできなさそうなので、ここでコメントします。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_ja.json#L93

「読み込み中…」にしない理由を教えていただけますでしょうか。
`Loading...`のままでもよいかもしれませんが、翻訳するorしないの線引きをどこでやっているのかがわかりません。

2021-03-08 06:51 UTC, kobaji commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
変更していない行に対してコメントできなさそうなので、ここでコメントします。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_ja.json#L97

PipelineRunなどのステータス絞り込み部分です。
Allでもよい気はしますが、「すべてのステータス」「すべて」の方が個人的にしっくりきます。いかがでしょうか。
すべての英語を日本語にしましょう、というわけではないですが、何か基準がほしいですね。整合性に問題が発生しそう。

2021-03-08 06:51 UTC, kobaji commented on src/nls/messages_ja.json
>      "dashboard.graph.pan": "",
「Pan」のままよりかは「パン」の方がマシかもしれません。
ただ、「パン」っていう用語は私にとって初耳でした。
パンとは： https://www.weblio.jp/content/%E3%83%91%E3%83%B3%E3%83%8B%E3%83%B3%E3%82%B0
グラフを作った時、左右にスクロールするようなものだと思います。
「現在Pan機能は実装されていないので、""にする。実装されたら使われている場所を確認し、翻訳するか決める」というのも選択肢としてアリだと思いますが、その旨チケットかどこかに明記して忘れずに済むようにしてもらいたいです。

2021-03-08 06:51 UTC, kobaji commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
変更していない行に対してコメントできなさそうなので、ここでコメントします。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_ja.json#L134

Tektonのロゴに関するalt属性です。
alt属性： https://www.seohacks.net/blog/971/

> 「画像が閲覧できない環境下でも、その情報が正しく理解される」ような代替テキスト情報がalt属性には記述されなければなりません。

　
ということなので日本語の「Tektonロゴ」の方が良いと思いますがいかがでしょうか。

2021-03-08 06:51 UTC, kobaji commented on src/nls/messages_ja.json
> +    "dashboard.run.duration": "継続時間：{duration}",
「継続」という用語を使った意図を知りたいです。

以下との違いがわかるとなお嬉しいです。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_ja.json#L203

2021-03-08 06:51 UTC, kobaji commented on src/nls/messages_ja.json
> +    "dashboard.skipToContent": "スキップしてメインコンテンツへ",
ヘッダーの`Tekton Dashboard`っていう部分の情報です。
「メインコンテンツへ」の方が、より日本語らしいと思うのですが、いかがでしょうか。

2021-03-08 06:51 UTC, kobaji commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
変更していない行に対してコメントできなさそうなので、ここでコメントします。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_ja.json#L204


翻訳しない理由を教えていただけますでしょうか。
以下と同様、「実装されたら`""`が使われている部分を発見し、翻訳するか決める」というのも選択肢としてアリだと思いますが、その旨チケットかどこかに明記して忘れずに済むようにしてもらいたいです。
https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_ja.json#L99

2021-03-08 06:51 UTC, kobaji commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
変更していない行に対してコメントできなさそうなので、ここでコメントします。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_ja.json#L243


`:`(半角コロン)は、日本語では全角にするルールなので`：`(全角コロン)にしてください。


参考： messages_en.json
https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/nls/messages_en.json#L243

2021-03-08 06:56 UTC, kobaji requested changes
以下のコメント、Resolve機能がつかえないみたいなので、Resolve機能が使えるように[投稿](https://github.com/fujitsu-cdf/dashboard/pull/23#discussion_r589888735)しなおしました。

```
細かいですが、PR文の「Changes」部分

add translation terms to empty columns
↓
Add translation terms to empty columns
`add`は`Add`の方が適切に見えます。ここで作成した文章と全く同じでコミュニティ用PRを発行してもらうので、ここはできるだけきれいに書いてもらいたいです。
指摘が妥当でなかったらすみません。(`add`の方が適切だったらすみません)
```

2021-03-08 06:59 UTC, kobaji reviewed
@mishima-haruka (cc @Martsings )
term.tsvを見ました。こちらに関しては指摘コメントございません。

2021-03-08 09:14 UTC, mishima-haruka commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
ご指摘ありがとうございます。ご意見の通りだと思いますので頂いた内容で修正します。

2021-03-08 09:22 UTC, mishima-haruka commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
この箇所についても馬さんが以前対応された箇所なので飛ばしていました。どのように使われているかGUIで見ていないため、翻訳妥当性については私から何も言えません。@Martsings さんお答えいただけますか？

2021-03-09 00:52 UTC, Martsings commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
@kobaji 確かに初回翻訳のレビュー時に小林さんと山本さんとDashboardを確認しながら翻訳しない方針にしたと思いますが、違いましたか？

2021-03-09 01:03 UTC, mishima-haruka commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
ご指摘ありがとうございます。使用箇所を考慮できていなかったので頂いた内容で修正します。

2021-03-09 01:04 UTC, mishima-haruka commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
ご指摘ありがとうございます。使用箇所を考慮できていなかったので頂いた内容で修正します。

2021-03-09 01:05 UTC, mishima-haruka commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
ご指摘ありがとうございます。ご意見の通りだと思いますので頂いた内容で修正します。

2021-03-09 01:10 UTC, mishima-haruka commented on src/nls/messages_ja.json
> +    "dashboard.run.duration": "継続時間：{duration}",
ご指摘ありがとうございます。他箇所で同単語があることを調べていませんでした。durationそのままの意味で訳しましたが、ご指摘の通り既存の訳が存在するようですのでそちらで修正します。

2021-03-09 01:15 UTC, mishima-haruka commented on src/nls/messages_ja.json
> +    "dashboard.skipToContent": "スキップしてメインコンテンツへ",
ご指摘ありがとうございます。ご指摘ありがとうございます。ご意見の通りだと思いますので頂いた内容で修正します。

2021-03-09 01:19 UTC, kobaji commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
@Martsings 
確かに確認したうえで翻訳しない形にした気はします。その時の理由は覚えていますでしょうか？
私は理由を覚えていないのですが、多分以下だと思います。

上記メッセージは以下ファイルで使われているが、現在のGUIから該当する部分を見つけることができず、まだ実装されていないと考えられるため。

https://github.com/fujitsu-cdf/dashboard/blob/bb9098c6ac66d6d248dc9e4149fe9692232d7956/src/containers/About/About.js#L55-L56

「現在のダッシュボードに使われていないため、どのように翻訳すればよいかわからない。実装されたら""が使われている部分を発見し、翻訳するか決める」というのも選択肢としてアリだと思います。その場合、その旨チケットかどこかに明記して忘れずに済むようにしてもらいたいです。

2021-03-09 01:24 UTC, mishima-haruka commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
ご指摘ありがとうございます。使用箇所を考慮できていなかったので頂いた内容で修正します。

2021-03-09 01:25 UTC, mishima-haruka commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
ご指摘ありがとうございます。ご意見の通りだと思いますので頂いた内容で修正します。

2021-03-09 01:28 UTC, mishima-haruka commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
ご指摘ありがとうございます。コロンについて考慮せずスキップしていました。コロンを全角にしたものを日本語訳に追加します。

2021-03-09 01:35 UTC, mishima-haruka commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
ご指摘ありがとうございます。線引きについては明確なものはありませんでした。Loadingについては日本語より英語の表記に目が慣れてしまっていることもあり、自分も翻訳しないと判断したんだと思います。
日本語訳としてご指摘の通りだと思うので、修正します。

2021-03-09 01:37 UTC, Martsings commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
> 現在のダッシュボードに使われていないため、どのように翻訳すればよいかわからない。実装されたら""が使われている部分を発見し、翻訳するか決める

小林さんの言う通り当時もこのような考えによって翻訳しなかったです。

> その場合、その旨チケットかどこかに明記して忘れずに済むようにしてもらいたいです

了解しました。今回を契機にチケットに追記すると思います。

2021-03-09 01:38 UTC, mishima-haruka commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
ご指摘ありがとうございます。「すべて」で修正したいと思います。

2021-03-09 01:39 UTC, mishima-haruka commented on src/nls/messages_ja.json
>      "dashboard.graph.pan": "",
ご指摘ありがとうございます。チケットに明記する形で今回は対応します。

2021-03-09 01:40 UTC, mishima-haruka commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
ご指摘ありがとうございます。panと同様の対応にします。

2021-03-09 01:41 UTC, mishima-haruka commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
ご指摘ありがとうございます。修正します。

2021-03-09 02:15 UTC, kobaji requested changes

2021-03-09 02:15 UTC, kobaji commented on src/nls/messages_ja.json
>      "dashboard.createTaskRun.invalidTask": "Taskを空にすることはできません",
PR文について細かいですが、ここでコメントさせてください。

add translation terms to empty columns
↓
Add translation terms to empty columns
addはAddの方が適切に見えます。ここで作成した文章と全く同じでコミュニティ用PRを発行してもらうので、ここはできるだけきれいに書いてもらいたいです。
指摘が妥当でなかったらすみません。(addの方が適切だったらすみません)

2021-03-10 02:23 UTC, kobaji commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
指摘がわかりにくくてすみません。修正箇所を誤っているように見えます。

61行目と77行目は現状このようになっているようなので、修正お願いします。

```
# 61行目
    "dashboard.createPipelineRun.title": "",
↓
    "dashboard.createPipelineRun.title": "PipelineRunを作成",
# 77行目
    "dashboard.createTaskRun.title": "PipelineRunを作成",
↓
    "dashboard.createTaskRun.title": "TaskRunを作成",
```

2021-03-10 07:31 UTC, mishima-haruka commented on src/nls/messages_ja.json
> -    "dashboard.createTaskRun.title": "",
読み間違えていました。ご指摘ありがとうございます。

2021-03-10 07:50 UTC, kobaji approved these changes

2021-03-10 08:14 UTC, merged