ボタン側にマージンを追加
fujitsu-cdf/dashboard pull request #24
Opened 2021-09-28 02:10 UTC by yamaken1343

実機で検証できてないので誰かお願いしたいです

フィルタは .bx--tagというclass（とか）が指定されており、全てをクリアのボタンはbx--btnというclass（とが）が指定されている

bx--tagにはmarginが指定されているが、bx--btnにはそれがない
2行になった際に、tagが左にあるときはマージンが追加されるが、ないときはされないため、位置が変わったように見える

2021-10-06 09:17 UTC, kobaji commented
PRありがとうございます。
マージ先ブランチですが、mainブランチから9961-prブランチを作成したうえで、9961-prをマージ先ブランチにしていただけますか？

http://10.125.71.194:3000/projects/cdf/wiki/%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E6%88%A6%E7%95%A5
に従っていただけると幸いです。

目的：
- コミュニティのお作法で2個以上コミットがある場合、squashする必要があるが、それを実現するため。
- wkブランチにコミュニティのmainブランチにPRを発行した場合、wkブランチに2個以上コミットがあると、squashしたときに作業内容が丸められてしまい、今後振り返りや分析したいときに困りうると考えているため。

ただこの運用方法は正直煩わしいと思いますし、改善を検討する必要もあると思いますので、やりにくいようでしたらコメントいただけると幸いです。

2021-10-06 09:18 UTC, kobaji requested changes

2021-10-06 09:18 UTC, kobaji commented on packages/components/src/components/LabelFilter/LabelFilter.scss
>        flex-shrink: 0;
PRありがとうございます。この行には関係ないですが…


マージ先ブランチですが、mainブランチから9961-prブランチを作成したうえで、9961-prをマージ先ブランチにしていただけますか？

http://10.125.71.194:3000/projects/cdf/wiki/%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E6%88%A6%E7%95%A5
に従っていただけると幸いです。

目的：
- コミュニティのお作法で2個以上コミットがある場合、squashする必要があるが、それを実現するため。
- wkブランチにコミュニティのmainブランチにPRを発行した場合、wkブランチに2個以上コミットがあると、squashしたときに作業内容が丸められてしまい、今後振り返りや分析したいときに困りうると考えているため。

ただこの運用方法は正直煩わしいと思いますし、改善を検討する必要もあると思いますので、やりにくいようでしたらコメントいただけると幸いです。

2021-10-06 09:41 UTC, mikkosalvador commented
```scss
    .bx--tag {
      flex-shrink: 0;
      margin: $spacing-05 $spacing-03 0 0;
    }

    .bx--btn {
      flex-shrink: 0;
      margin: $spacing-05 $spacing-03 0 0;
    }
```
Seems like it can be compressed to:
```scss
    .bx--tag, .bx--btn {
      flex-shrink: 0;
      margin: $spacing-05 $spacing-03 0 0;
    }
```
Also, I am not sure if the the other margins are needed. Only the top margin seems to be relevant for this specific issue.
また、他のmarginが必要かどうかもわかりません。このissueに関連しているのはmargin-topだけのようです。

Either way, please create a pull request to get feedback from the maintainers.
いずれにしても、メンテナからフィードバックを得るためにPRを行ってください。

2021-10-13 06:49 UTC, yamaken1343 commented
tagが本体1.5remでmerginが1rem、btnが本体2remなので、marginを0.75remにすると計算は合うはずなんですが、合わない（数値上は合うが、画面上で1pxずれる）
ので暫定で-1pxしている

2021-10-15 08:28 UTC, mikkosalvador commented
I checked it and it seems that there are no layout shifts anymore. The flexbox rows are uneven (40px for `bx--tag` only rows, and 43px for rows with `bx--btn` only) but it seems to adjust the alignment when the button wraps to the next row so it's no problem.

I'm not sure with `$spacing-04 - 1px` instead of just `11px` since it is still hardcoding the `1px`. Please push the commit to the PR and notify the maintainers of the changes to get their thoughts.

2021-10-19 02:39 UTC, yamaken1343 commented
マージされたのでクローズ

2021-10-19 02:39 UTC, closed without merging